### ISSUE TITLE
Restrict max-width of Match Report and Blog images

### ISSUE THREAD

**Issue by grahammcculloch** [cshc/cshc-web#2]
e.g. '/matches/2625/'

Need some appropriate CSS (and probably a useful class name so we can make the CSS as generic as possible)

**Comment by grahammcculloch** [comment]
No need to add anything for blog entries - already covered by the following CSS rule in `/static/vendor/zinnia/theme/css/screen.scss`:
```css
.zinnia .entry-image img {
    width: 100%;
}
```
